language: node_js
node_js:
  - "8.9.1"

branches:
  only:
    - master

before_install:
  - npm install bower -g
  - npm install gulp -g

script:
  - npm install
  - gulp

cache:
  directories:
  - node_modules
  
deploy:
  provider: pages
  local-dir: dist
  repo: Glitch0011/canicall.info
  fqdn: canicall.info
  skip-cleanup: true
  github-token: $SECRET_GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
